name: ML Pipeline CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 12 * * *'

jobs:
  train-and-validate:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run full pipeline update
      run: python run.py -mode update

    - name: Generate summary report
      run: python run.py -mode summary

    - name: Run tests
      run: |
        python -m pytest tests/ -v

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ml-artifacts
        path: |
          logs/
          models/
          reports/
        retention-days: 7
